<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>sql-sc</AssemblyName>
    <RootNamespace>SqlSc.Cli</RootNamespace>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>sql-sc</ToolCommandName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SqlSc.Core\SqlSc.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\THIRD-PARTY-NOTICES.md" Link="THIRD-PARTY-NOTICES.md" CopyToPublishDirectory="PreserveNewest" ExcludeFromSingleFile="true" />
  </ItemGroup>

</Project>
